version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - 5432:5432

  node:
    build: ./
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./:/app/:rw
